### ISSUE TITLE
Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by paulnagle** [jbraswell/tomato#22]
Hey Jonathan..   I was hoping to use the tomato server for a few things on the websites I look after.. However I'm getting a request denied when I try to request json from the tomato server

Failed to load https://tomato.na-bmlt.org/main_server/client_interface/json/?switcher=GetSearchResults&geo_width_km=25&long_val=-9.0308069&lat_val=51.5779958&sort_key=sort_results_by_distance&data_field_key=meeting_name,weekday_tinyint,start_time,location_text,location_street,location_info,distance_in_km,latitude,longitude,formats&get_used_formats: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://www.nasouth.ie' is therefore not allowed access.

The request is just done with plain jquery getJSON.  It would be great if you would consider implementing jsonp, that would avoid this whole issue for me.

Thanks!

**Comment by radius314** [comment]
Just add CORS all header.

**Comment by paulnagle** [comment]
Is that header added to the server response, or to my jquery request?

**Comment by radius314** [comment]
It needs to be added to the server.  The sandwich had this hardcoded, which I think should be fine.  

ref: https://github.com/radius314/sandwich/blob/3026823f962058ead5c1bbcd3aa2912c1e361f35/lib/response.js#L11

**Comment by jbraswell** [comment]
Yeah, pretty sure this is a server thing. I’ve dealt with this before in other Django projects. I’ll take a look at it for you soon.

**Comment by jbraswell** [comment]
@paulnagle 

I just kicked off a rolling update to deploy this: https://github.com/jbraswell/tomato/compare/6c178b3eaf6b...0c4ecfc48c6b

Let me know if this helps.

**Comment by paulnagle** [comment]
Thanks @jbraswell that's fixed it!
