### ISSUE TITLE
Implement recursive as the root server does

### ISSUE THREAD

**Issue by radius314** [jbraswell/tomato#26]
Recursive allows you to specify a single service body ID or IDs and if recursive=1 it will also include all the children nodes.  Keep in mind you may have multiple layers.

**Comment by jbraswell** [comment]
Simple enough. Probably can take care of this this weekend.

**Comment by jbraswell** [comment]
Does the recursive flag also apply to exclude filters? By exclude I mean passing in negative service body ids.

**Comment by radius314** [comment]
Ask @littlegreenviper

**Comment by LittleGreenViper** [comment]
I believe so. The - is not taken into account until the value is directly considered. Easy enough to test.

**Comment by jbraswell** [comment]
Implemented:  https://github.com/jbraswell/tomato/compare/209b2c0a66ff...d3d1e08b2b0c

**Comment by jbraswell** [comment]
This has been deployed.
