### ISSUE TITLE
Root Server ID should be a URI, not an Int, or we should add a URI string

### ISSUE THREAD

**Issue by LittleGreenViper** [jbraswell/tomato#27]
Just looked at a dump: https://tomato.na-bmlt.org/main_server/client_interface/csv/?switcher=GetSearchResults

I noticed that the last column is an integer ID.

The root_server_uri is something I concocted in order to be able to quickly follow up meeting info.

I initially wanted to use it to allow us to match up meeting formats with he server-defined ones, but it may also be useful with Yap.

**Comment by LittleGreenViper** [comment]
Also, just to add to the misery, in the latest version of the Root Server (not released yet, but it will be 2.10.3), I have added a last column: "format_shared_id_list", which has the meeting formats, but listed as a CSV list of integers (each a format shared ID). I use this internally to make sure the proper checkbox is selected when we have multiple formats with the same key, but they could be very useful outside the admin interface.

**Comment by jbraswell** [comment]
The root_server_id is a tomato-specific value, and I'd like to keep it.

I will add root_server_uri to results.

Going to create a new issue for format_shared_id_list.

**Comment by jbraswell** [comment]
https://github.com/jbraswell/tomato/commit/5b6a4c1780c1d44be546ead88c2689a0b52263e3
