### ISSUE TITLE
Add format_shared_id_list for compatibility with upcoming root server release

### ISSUE THREAD

**Issue by jbraswell** [jbraswell/tomato#28]

**Comment by jbraswell** [comment]
From @LittleGreenViper 
>Also, just to add to the misery, in the latest version of the Root Server (not released yet, but it will be 2.10.3), I have added a last column: "format_shared_id_list", which has the meeting formats, but listed as a CSV list of integers (each a format shared ID). I use this internally to make sure the proper checkbox is selected when we have multiple formats with the same key, but they could be very useful outside the admin interface.

**Comment by jbraswell** [comment]
@LittleGreenViper To clarify, this is for GetSearchResults? Do you have a 2.10.3 instance of the root server that you can share with me privately?

**Comment by LittleGreenViper** [comment]
I keep the master up to date with the current work (unless the build is really broken). The release branch holds the tagged releases. I update it whenever I do a release.

**Comment by jbraswell** [comment]
https://github.com/jbraswell/tomato/compare/72affd1e36a91cc4b8d398a319d937ee58cdeb69...08d0df6a74e347e2f523a51e7ce1eac916c844c0

deployed
