### ISSUE TITLE
implement kml endpoint

### ISSUE THREAD

**Issue by radius314** [jbraswell/tomato#29]
Would like it for https://tomato.na-bmlt.org/main_server/client_interface/kml/?switcher=GetSearchResults&sort_results_by_distance=1&long_val=-72.0468164&lat_val=41.8275622&geo_width=-50&weekdays=2 to be able to surface results.

**Comment by jbraswell** [comment]
This has been implemented.

**Comment by radius314** [comment]
👍 lgtm
