### ISSUE TITLE
Implement SearchString parameter for GetSearchResults

### ISSUE THREAD

**Issue by jbraswell** [jbraswell/tomato#9]
Possible Parameters
- SearchString
- SearchString + StringSearchIsAnAddress=1
- SearchString + StringSearchIsAnAddress=1 + SearchStringRadius
- SearchString + SearchStringAll=1
- SearchString + SearchStringExact=1

If `SearchStringIsAnAddress == 1`, then the Google Maps API is used to find a latitude and longitude based on that address. If `SearchStringRadius` is set, then we find meetings within that distance from the latitude and longitude. If `SearchStringRadius` is not set, then we increase the search radius until we find 10 meetings. Additional fields are also returned for each meeting: distance_in_km and distance_in_miles.

If the search radius is not specified, I don't think we need to do this incremental increasing of the radius until we find 10 minutes. Instead, we can just find the 10 closest meetings by sorting by distance.

In all other cases (`SearchString` without options, `SearchStringAll`, and `SearchStringExact`) BMLT is performing the search in-memory outside of a sql database. 

When just SearchString is specified, with no other options, it attempts a metaphone search if the language supports it. It's searching all of the text fields. It basically concatenates them all together and then performs the search. Not sure how many words have to be found.

If SearchStringAll is set, then all of the words in the SearchString have to be found.

SearchStringExact is a literal string match.

http://maps.googleapis.com/maps/api/geocode/xml?address=##SEARCH_STRING##&sensor=false

**Comment by jbraswell** [comment]
SearchString + StringSearchIsAnAddress has been implemented.

**Comment by LittleGreenViper** [comment]
The regular search string is a metaphone. Exact disables metaphone.

**Comment by LittleGreenViper** [comment]
OK. You almost have it right. The auto-radius is different, though.

If it is negative, then that is the (rough) number of meetings to find. If negative, it is always an integer. Km and Mi don't matter when negative.

Not specified is the server default auto-radius (usually -10).

I explain that here: https://bmlt.magshare.net/how-auto-radius-works/

If you don't specify SearchStringExact=1, then it uses a metaphone token search. That's actually a bit awkward.

**Comment by LittleGreenViper** [comment]
Here's an SQL Haversine formula I use. Not sure if it works for postgres:

https://bitbucket.org/bmlt/bmlt-root-server/src/0d8b352330cbb52bf8f1360a42d2b04c9167ded2/main_server/server/c_comdef_server.class.php?at=Release&fileviewer=file-view-default#c_comdef_server.class.php-2588

**Comment by jbraswell** [comment]
Thanks for the clarification. I have search string radius stuff _almost_ working like that. I was just always getting the 10 nearest meetings rather than abs(SearchStringRadius) when it's negative. I can make a quick  change to use a negative SearchStringRadius as the LIMIT in the query.

I just implemented SearchString + SearchStringAll. It's not yet using metaphone/fuzzy matching. I'm still figuring out how to do that.

**Comment by jbraswell** [comment]
This is done. It's not _exactly_ the same as what's in BMLT, but it's pretty darn close.
